In [51]:
#Dependencies
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [52]:
#Read CSV
data_path="data.csv"
data=pd.read_csv(data_path)
data.drop(['type', 'species', 'coat', 'published_at', 'distance', 'search_address', 'search_city', 'search_state'], axis=1, inplace =True)
data.rename(columns={'Unnamed: 0':'dog_id'},inplace=True)
data.head()

,dog_id,url,age,gender,size,name,breeds.primary,breeds.secondary,breeds.mixed,breeds.unknown,...,environment.cats,contact.address.address1,contact.address.address2,contact.address.city,contact.address.state,contact.address.postcode,animal_id,primary_photo_cropped.full,Latitude,Longitude
0,0,https://www.petfinder.com/dog/merry-lee-523247...,Adult,Female,Medium,Merry Lee,Labrador Retriever,Terrier,True,False,...,0,0,0,Palmetto,GA,30268,52324701,0,33.517891,-84.669655
1,1,https://www.petfinder.com/dog/cedric-52324702/...,Adult,Male,Large,Cedric,Pointer,American Bulldog,True,False,...,0,0,0,Palmetto,GA,30268,52324702,0,33.517891,-84.669655
2,2,https://www.petfinder.com/dog/trooper-52324703...,Adult,Male,Large,Trooper,Staffordshire Bull Terrier,Bull Terrier,True,False,...,0,0,0,Palmetto,GA,30268,52324703,0,33.517891,-84.669655
3,3,https://www.petfinder.com/dog/cyndi-52324704/g...,Adult,Female,Large,Cyndi,American Staffordshire Terrier,0,False,False,...,False,0,0,Palmetto,GA,30268,52324704,0,33.517891,-84.669655
4,4,https://www.petfinder.com/dog/enzo-52324705/ga...,Young,Male,Medium,Enzo,Coonhound,Labrador Retriever,True,False,...,0,0,0,Palmetto,GA,30268,52324705,0,33.517891,-84.669655

In [53]:
#Create Database Connection
from config import password
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost/Doghouse')
con = engine.connect()

In [54]:
#Load Data Frames into Database
data.to_sql(name='data', con=engine, if_exists='append', index=False)

In [55]:
#Confirm Data Frames are in Database
engine.table_names()

['data']